### PR TITLE
More improvments

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks Max!

Just a few questions, out of curiosity.

- Doesn't the compiler optimize expressions such as `% 128` into `& 0x7f` already?

- Why did you turn `precomp_base` into an inline function? Is that the right thing to do for any constant array?

It is critical for `cmov` to be constant-time, so that shouldn't be changed to `select`.

**Comment by jedisct1** [comment]
Answering my first question: it doesn't:

```wasm
 (func $assembly/index/add (; 0 ;) (type $III) (param $0 i64) (param $1 i64) (result i64)
  get_local $0
  get_local $1
  i64.const 128
  i64.rem_u
  i64.add
 )
```

Cranelift will optimize this, and that's the first thing JITs will also do, but good to know that binaryen doesn't!

**Comment by MaxGraey** [comment]
> Doesn't the compiler optimize expressions such as % 128 into & 0x7f already?

  It optimize it, but only for unsigned values. But for speed up optimized compilation I think better do it manually, this manual optimization does not affect readability.

> Why did you turn precomp_base into an inline function? Is that the right thing to do for any constant array?

This could improve compilation speed if `precomp_base` not using. So this huge table lazily parsed and compile only when `scalarmultBase` using somewhere.

**Comment by MaxGraey** [comment]
`select` always compiled to `cmov` instruction. So it constant time. All VMs currently support it and compile to condisional mov instruction

**Comment by jedisct1** [comment]
Does the WebAssembly spec requires it to be constant time? I'm not really confident that we should rely on it being turned into `cmov`.

**Comment by MaxGraey** [comment]
> Does the WebAssembly spec requires it to be constant time? I'm not really confident that we should rely on it being turned into cmov.

Sure I can revert this change.
btw binaryen can't simplify `x % 128` to `x & 127` for `u64`. That's strange. For `u32` this is done

**Comment by jedisct1** [comment]
Even if it has been the case so far, `CMOV` has never been guaranteed by Intel to be constant-time. Not sure about other architectures either. So, yes, reverting that one feels safer.

**Pull request merged**
